"""Stage 4 — Output Generator.

Writes a README.md (and optional JSON sidecar) capturing architecture,
data flow, key files, Mermaid diagram, guided file-by-file tour, and a
**runtime benchmark table** for the cracked target repo.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from jinja2 import Template
from rich.console import Console

from .benchmark import format_cost, format_seconds
from .config import Settings
from .models import ArchitectureReport, BenchmarkStats, RepoMap

console = Console()

README_TEMPLATE = Template(
    """\
# Architecture Walkthrough — {{ repo_name }}

> Generated by **CodeCracker** on {{ generated_at }}  
> Source: [{{ repo_url }}]({{ repo_url }})  
> Synthesis provider: `{{ provider }}`

---

## Overview

{{ overview }}

---

## Architecture & Data Flow of the Tool

```
[ GitHub Public Repo URL ]
            │
            ▼
┌──────────────────────────────────────┐
│ 1. Git Cloner & AST Parser Module    │
│    (Filters out non-code, captures   │
│     imports & module call-graphs)    │
└──────────────────────────────────────┘
                   │
                   ▼
┌──────────────────────────────────────┐
│ 2. Context Builder & Structural Map  │
│    (Generates folder tree & metadata)│
└──────────────────────────────────────┘
                   │
                   ▼
┌──────────────────────────────────────┐
│ 3. LLM Prompt Strategy Engine        │
│    (Generates Architecture Summary,  │
│     Mermaid.js Flow, & Guided Tour)  │
└──────────────────────────────────────┘
                   │
                   ▼
┌──────────────────────────────────────┐
│ 4. Output Generator                  │
│    (Writes generated README.md)      │
└──────────────────────────────────────┘
```

---

## Execution efficiency (this run)

| Target Repo | Files Analyzed | Time (Heuristic) | Time (LLM) | Approx. Token Cost |
|-------------|----------------|------------------|------------|--------------------|
| [{{ benchmark.target_repo }}]({{ repo_url }}) | {{ benchmark.files_analyzed }} | {{ heuristic_time }}{% if provider == 'heuristic' %}{% else %} (est.){% endif %} | {{ llm_time }}{% if provider != 'heuristic' %}{% else %} (est.){% endif %} | {{ token_cost }}{% if provider == 'heuristic' %} (est.){% endif %} |

{{ benchmark.notes }}

Stage timings (clone={{ clone_s }}, map={{ map_s }}, synthesize={{ synth_s }}, write={{ write_s }}).

---

## Architecture Summary

{{ architecture_summary }}

---

## Data Flow

{{ data_flow }}

---

## Mermaid Architecture Diagram

```mermaid
{{ mermaid }}
```

---

## Key Files

| Path | Role |
|------|------|
{% for kf in key_files -%}
| `{{ kf.path }}` | {{ kf.role }} |
{% endfor %}

---

## Guided Walkthrough (file by file)

Open these files **in order**. Each step tells you *why* this file matters and
*what to look for* before moving on — the hands-on way to learn a legacy /
third-party codebase.

{% for step in guided_tour %}
### Step {{ step.order }} — {{ step.title }}

**File:** `{{ step.path }}`

{{ step.why }}

**What to look for:**
{% for item in step.what_to_look_for -%}
- {{ item }}
{% endfor %}
{% if step.next_hint %}
→ *{{ step.next_hint }}*
{% endif %}
{% endfor %}

---

## How to Extend This Understanding

{{ how_to_extend }}

---

## Repo Snapshot

| Metric | Value |
|--------|-------|
| Parsed source files | {{ file_count }} |
| Import edges | {{ edge_count }} |
| Languages | {{ languages }} |
| Entrypoints | {{ entrypoints }} |

### Folder tree

```
{{ tree_text }}
```

---

*This README was auto-generated to demonstrate guided architectural onboarding.
Re-run CodeCracker after major refactors to refresh the tour.*
"""
)


def render_readme(
    repo_map: RepoMap,
    report: ArchitectureReport,
    benchmark: BenchmarkStats,
) -> str:
    langs = ", ".join(
        f"{k}={v}"
        for k, v in sorted(
            repo_map.language_counts.items(), key=lambda kv: -kv[1]
        )
    )
    return README_TEMPLATE.render(
        repo_name=repo_map.repo_name,
        repo_url=repo_map.repo_url,
        generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        provider=report.provider,
        overview=report.overview,
        architecture_summary=report.architecture_summary,
        data_flow=report.data_flow,
        mermaid=report.mermaid,
        key_files=report.key_files,
        guided_tour=report.guided_tour,
        how_to_extend=report.how_to_extend,
        file_count=len(repo_map.files),
        edge_count=len(repo_map.edges),
        languages=langs or "—",
        entrypoints=", ".join(f"`{e}`" for e in repo_map.entrypoints[:8]) or "—",
        tree_text="\n".join(repo_map.tree_text.splitlines()[:80]),
        benchmark=benchmark,
        heuristic_time=format_seconds(benchmark.time_heuristic_s),
        llm_time=format_seconds(benchmark.time_llm_s),
        token_cost=format_cost(benchmark.approx_token_cost_usd),
        clone_s=format_seconds(benchmark.clone_s),
        map_s=format_seconds(benchmark.map_s),
        synth_s=format_seconds(benchmark.synth_s),
        write_s=format_seconds(benchmark.write_s),
    )


def write_outputs(
    repo_map: RepoMap,
    report: ArchitectureReport,
    settings: Settings | None = None,
    out_dir: Path | None = None,
    benchmark: BenchmarkStats | None = None,
) -> Path:
    """Write README.md + report.json; return the output directory."""
    settings = settings or Settings()
    settings.ensure_dirs()

    if benchmark is None:
        from .benchmark import build_benchmark

        benchmark = build_benchmark(
            repo_map, report, clone_s=0.0, map_s=0.0, synth_s=0.0, write_s=0.0
        )

    slug = repo_map.repo_name.replace("/", "__")
    dest = out_dir or (settings.output_dir / slug)
    dest.mkdir(parents=True, exist_ok=True)

    readme_path = dest / "README.md"
    readme_path.write_text(
        render_readme(repo_map, report, benchmark), encoding="utf-8"
    )

    sidecar = {
        "repo_url": repo_map.repo_url,
        "repo_name": repo_map.repo_name,
        "provider": report.provider,
        "key_files": report.key_files,
        "guided_tour": [
            {
                "order": s.order,
                "path": s.path,
                "title": s.title,
                "why": s.why,
                "what_to_look_for": s.what_to_look_for,
                "next_hint": s.next_hint,
            }
            for s in report.guided_tour
        ],
        "mermaid": report.mermaid,
        "languages": repo_map.language_counts,
        "entrypoints": repo_map.entrypoints,
        "metadata": repo_map.metadata,
        "benchmark": benchmark.as_dict(),
    }
    (dest / "report.json").write_text(
        json.dumps(sidecar, indent=2), encoding="utf-8"
    )
    (dest / "prompt_context.txt").write_text(report.raw_prompt, encoding="utf-8")

    console.print(f"[green]✓[/] Wrote [bold]{readme_path}[/]")
    console.print(f"  also: {dest / 'report.json'}, {dest / 'prompt_context.txt'}")
    return dest
